2024-11-30 12:25:03,021 - INFO - Imported existing <module 'comtypes.gen' from 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI264202\\comtypes\\gen\\__init__.pyc'>
2024-11-30 12:25:03,022 - INFO - Creating writeable comtypes cache directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\comtypes_cache\yto_wechart-312'
2024-11-30 12:25:03,022 - INFO - Using writeable comtypes cache directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\comtypes_cache\yto_wechart-312'
2024-11-30 12:29:13,560 - INFO - Imported existing <module 'comtypes.gen' from 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI212362\\comtypes\\gen\\__init__.pyc'>
2024-11-30 12:29:13,560 - INFO - Using writeable comtypes cache directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\comtypes_cache\yto_wechart-312'
2024-11-30 12:30:15,300 - INFO - Imported existing <module 'comtypes.gen' from 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI279442\\comtypes\\gen\\__init__.pyc'>
2024-11-30 12:30:15,301 - INFO - Using writeable comtypes cache directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\comtypes_cache\yto_wechart-312'
2024-11-30 12:31:13,833 - INFO - Imported existing <module 'comtypes.gen' from 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI21122\\comtypes\\gen\\__init__.pyc'>
2024-11-30 12:31:13,834 - INFO - Using writeable comtypes cache directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\comtypes_cache\yto_wechart-312'
2024-11-30 12:34:04,030 - INFO - Imported existing <module 'comtypes.gen' from 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI174682\\comtypes\\gen\\__init__.pyc'>
2024-11-30 12:34:04,031 - INFO - Using writeable comtypes cache directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\comtypes_cache\yto_wechart-312'
2024-11-30 12:34:39,770 - INFO - Imported existing <module 'comtypes.gen' from 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI84482\\comtypes\\gen\\__init__.pyc'>
2024-11-30 12:34:39,770 - INFO - Using writeable comtypes cache directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\comtypes_cache\yto_wechart-312'
2024-11-30 12:37:34,475 - INFO - Imported existing <module 'comtypes.gen' from 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI158362\\comtypes\\gen\\__init__.pyc'>
2024-11-30 12:37:34,476 - INFO - Using writeable comtypes cache directory: 'C:\Users\ADMINI~1\AppData\Local\Temp\comtypes_cache\yto_wechart-312'
2024-11-30 12:37:34,518 - INFO - Could not import comtypes.gen._944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0: No module named 'comtypes.gen._944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0'
2024-11-30 12:37:34,519 - INFO - # Generating comtypes.gen._944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0
2024-11-30 12:37:34,547 - INFO - # Generating comtypes.gen.UIAutomationClient
2024-11-30 12:37:34,550 - INFO - Could not import comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0: No module named 'comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0'
2024-11-30 12:37:34,551 - INFO - # Generating comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0
2024-11-30 12:37:34,554 - INFO - # Generating comtypes.gen.stdole
2024-11-30 12:37:38,136 - INFO - 微信窗口初始化成功
2024-11-30 12:37:38,160 - INFO - 会话列表初始化成功
2024-11-30 12:37:38,756 - INFO - 浏览器初始化成功
2024-11-30 12:38:01,574 - INFO - 从群 1 提取到订单号: ['YT1900126038163']
2024-11-30 12:38:01,574 - INFO - 消息已加入微信队列: YT1900126038163 拦截
2024-11-30 12:38:06,728 - INFO - 消息已发送到圆通系统: YT1900126038163 拦截
2024-11-30 12:38:22,498 - INFO - 获取到yto消息: YT1900126038163 test
2024-11-30 12:38:27,499 - INFO - 消息已加入圆通队列: YT1900126038163 test
2024-11-30 12:38:32,658 - INFO - 微信消息已发送到群 1: YT1900126038163 test
2024-11-30 12:38:46,509 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0931E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:38:50,610 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0933C20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:38:54,705 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0933980>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:38:58,799 - ERROR - 获取圆通消息失败: HTTPConnectionPool(host='localhost', port=49677): Max retries exceeded with url: /session/b8ec1bba6a637ae9a0720fe92556a013/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0932D50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-11-30 12:39:08,385 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0948080>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:39:12,453 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0948680>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:39:16,526 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA09488C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:39:20,628 - ERROR - 获取圆通消息失败: HTTPConnectionPool(host='localhost', port=49677): Max retries exceeded with url: /session/b8ec1bba6a637ae9a0720fe92556a013/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0948AD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-11-30 12:39:30,238 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0948320>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:39:34,305 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0948F50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:39:38,383 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0949280>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:39:42,430 - ERROR - 获取圆通消息失败: HTTPConnectionPool(host='localhost', port=49677): Max retries exceeded with url: /session/b8ec1bba6a637ae9a0720fe92556a013/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA09495B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-11-30 12:39:52,022 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA09489E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:39:56,063 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0949AF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:40:00,150 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0949D90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:40:04,216 - ERROR - 获取圆通消息失败: HTTPConnectionPool(host='localhost', port=49677): Max retries exceeded with url: /session/b8ec1bba6a637ae9a0720fe92556a013/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094A090>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-11-30 12:40:13,774 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA09497C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:40:17,845 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094A540>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:40:21,930 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0933590>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:40:26,008 - ERROR - 获取圆通消息失败: HTTPConnectionPool(host='localhost', port=49677): Max retries exceeded with url: /session/b8ec1bba6a637ae9a0720fe92556a013/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0949EB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-11-30 12:40:35,591 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA09498B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:40:39,657 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0949310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:40:43,718 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0948FB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:40:47,789 - ERROR - 获取圆通消息失败: HTTPConnectionPool(host='localhost', port=49677): Max retries exceeded with url: /session/b8ec1bba6a637ae9a0720fe92556a013/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0948B30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-11-30 12:40:57,353 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA0948BC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:41:01,425 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094A5D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:41:05,485 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094A1E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:41:09,556 - ERROR - 获取圆通消息失败: HTTPConnectionPool(host='localhost', port=49677): Max retries exceeded with url: /session/b8ec1bba6a637ae9a0720fe92556a013/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094AA20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-11-30 12:41:19,133 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094A7E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:41:23,223 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094AE10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:41:27,302 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094AED0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:41:31,370 - ERROR - 获取圆通消息失败: HTTPConnectionPool(host='localhost', port=49677): Max retries exceeded with url: /session/b8ec1bba6a637ae9a0720fe92556a013/elements (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094B350>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2024-11-30 12:41:40,930 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094B020>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
2024-11-30 12:41:44,979 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AEA094B6B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ec1bba6a637ae9a0720fe92556a013/elements
